// The following addresses are from a json file called: ns2-mainnet.json

pragma solidity >=0.5.12;

// Autogenerated Solidity Tinlake Address Contract 
contract POOL_CONFIG {

    // precision
    uint256 constant public THOUSAND = 10 ** 3;
    uint256 constant public MILLION  = 10 ** 6;
    uint256 constant public WAD      = 10 ** 18;
    uint256 constant public RAY      = 10 ** 27;
    uint256 constant public RAD      = 10 ** 45;

    // Maker changelog 
    address constant MAKER_CHANGELOG = 0xdA0Ab1e0017DEbCd72Be8599041a2aa3bA7e740F;

    // Tinlake addresses CF4 
    address constant ROOT = 0x792164b3e10a3CE1efafF7728961aD506c433c18;
    address constant DROP = 0x931C3Ff1F5aC377137d3AaFD80F601BD76cE106e;
    address constant MGR = 0x45e17E350279a2f28243983053B634897BA03b64;
    address constant RESERVE = 0x8d9466346ea306F43b9203F53140C3EB6777a75F;
    address constant MEMBERLIST = 0xb7ee04cb62bFD87862e56E2E880b9EeB87aDf20F;
    address constant COORDINATOR = 0xb9575aD050263cC0A9E65B8bd6041DbF5e02bf1F; 
    address constant SENIOR_OPERATOR = 0xDeb6eEEF90bbb5be6A771250eb9bA8d0804c3F5D;
    address constant ASSESSOR = 0xe5B1C9DB5316350e1501ADe417cBe44d2D6A04Cd;
    address constant TRANCHE = 0x3bCe1712d1AaC8C9597Bc65F1c1630aF32F918B0;


    // MIP21 contracts RWA003-A
    address public constant MCD_JOIN = 0x4CCc7fED3912A32B6Cf7Db2FdA1554a9FF574099;
    address constant GEM = 0xDBC559F5058E593981C48f4f09fA34323df42d51;
    address public constant OPERATOR = 0x45e17E350279a2f28243983053B634897BA03b64; // MGR
    address public constant INPUT_CONDUIT = 0x45e17E350279a2f28243983053B634897BA03b64; // MGR
    address public constant OUTPUT_CONDUIT = 0x45e17E350279a2f28243983053B634897BA03b64; // MGR
    address public constant URN =  0x993c239179D6858769996bcAb5989ab2DF75913F;
    address public constant LIQ = 0x2881c5dF65A8D81e38f7636122aFb456514804CC; // MIP21-LIQ-ORACLE

    // changelog IDs
    bytes32 public constant dropID = "RWA003";
    bytes32 public constant joinID = "MCD_JOIN_RWA003_A";
    bytes32 public constant urnID = "RWA003_A_URN";
    bytes32 public constant inputConduitID = "RWA003_A_INPUT_CONDUIT";
    bytes32 public constant outputConduitID = "RWA003_A_OUTPUT_CONDUIT";
    bytes32 public constant pipID = "PIP_RWA003";

    // values, based on https://forum.makerdao.com/t/cf-drop-collateral-onboarding-risk-evaluation/5597
    bytes32 public constant ilk = "RWA003-A";
    // look up in https://ipfs.io/ipfs/QmefQMseb3AiTapiAKKexdKHig8wroKuZbmLtPLv4u2YwW
    uint256 public constant RATE = 1000000001847694957439350562; // 6% stability fee
    uint256 public constant DC = 2 * MILLION * RAD; // creditline: 2 mio
    uint256 public constant MAT = 105 * RAY / 100; // Min Vault CR of 105%
    uint256 public constant INITIAL_PRICE =  2_247_200 * WAD; // creditLine + 2 years of stability fee => 2000000 * 1.06^2
}
